# Generated by Django 5.1.7 on 2025-03-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medidas_clientes', '0005_pessoa_tamanho_blazer_pessoa_tamanho_blusa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
