# Generated by Django 5.1.7 on 2025-06-05 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medidas_clientes', '0006_pessoa_altura_pessoa_peso_pessoa_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
