# Generated by Django 5.1.7 on 2025-06-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medidas_clientes', '0007_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='altura',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
