# Generated by Django 5.1.7 on 2025-06-06 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medidas_clientes', '0008_alter_pessoa_altura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='observacao',
            field=models.TextField(blank=True),
        ),
    ]
