# Generated by Django 5.1.7 on 2025-06-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medidas_clientes', '0009_pessoa_observacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
